name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: check env
      run: env

    - name: check installed sdk
      run: ${ANDROID_HOME}/tools/bin/sdkmanager --list
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: |
         app/build/outputs/apk/debug/app-debug.apk
         app/mobile/
        retention-days: 5
