name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bundleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: |
         app/build/outputs/apk/debug/app-debug.apk
         app/mobile/build/outputs/bundles/debug/mobile-debug.aab
         app/mobile/release/mobile-release.aab
        retention-days: 5
